version: "3"
services:
  server:
    build: ./
    container_name: neuro_server
    working_dir: '/var/www/html'
    volumes:
      - './:/var/www/html'
    command: php -S 0.0.0.0:8000
    #command: bash -c "php artisan serve --host 0.0.0.0"
    #command: bash -c "php yii serve 0.0.0.0 --port=8000"
    ports:
      - 8001:8001
    networks:
      - neuro-network
networks:
  neuro-network:
    driver: bridge